# Generated by Django 3.2 on 2021-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user email')),
                ('password', models.CharField(max_length=65, verbose_name='user password')),
                ('phone_number', models.CharField(max_length=17, unique=True, verbose_name='user phone number')),
                ('name', models.CharField(max_length=20, verbose_name="user's name")),
                ('birthday', models.DateField(blank=True, null=True, verbose_name="user's birthday")),
                ('gender', models.CharField(default='N', max_length=1, verbose_name="user's gender")),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
